### ISSUE TITLE
Propper support to NavController

### ISSUE THREAD

**Issue by khalnadj2** [ismaeldivita/chip-navigation-bar#57] opened 2021-01-04 08:05 UTC
val navController = findNavController(R.id.nav_host_fragment)
 binding.bottomNav.setupWithNavController(navController)
 binding.bottomNav.setOnNavigationItemReselectedListener {/* NO-OP */ }

**Comment by ismaeldivita** [comment] 2021-05-06 13:38
duplicate of https://github.com/ismaeldivita/chip-navigation-bar/issues/20

**Closed by ismaeldivita** 2021-05-06 13:38 UTC
